title: Hello
description: This is a sample config file for NavigationPage # optional
greeting: Hello!
lang: en
# favicon: favicon.ico  # optional
groups:
  - name: Applications
    open-new-tab: true
    links:
      - name: Files
        link: http://example.com
        icon: ğŸ“
        desc: Manage your files
      - name: Album
        link: http://example.com
        icon: ğŸ“·
        desc: View your photos
      - name: EMail
        link: http://example.com
        icon: ğŸ“§
        desc: Send and receive emails
      - name: Calendar
        link: http://example.com
        icon: ğŸ“…
        desc: Check your schedule
      - name: Example Link
        link: https://example.com
        icon: evernote # material design icon name
        desc: Link Description
      - name: Example Link
        link: https://example.com
        icon: FireHydrant
        desc: Link Description
      - name: Example Link
        link: https://example.com
        icon: email
        desc: Link Description
      - name: Example Link
        link: https://example.com
        icon: MicrosoftOnenote
        desc: Link Description
      - name: Example Link
        link: https://example.com
        icon: Robber
      - name: Example Link
        link: https://example.com
        icon: EvPlugType1
      - name: Example Link
        link: https://example.com
        icon: FileImage
      - name: Example Link
        link: https://example.com
        icon: WeatherHazy
  - name: Bookmarks
    categories:
      - name: Social
        links:
          - name: Facebook
            link: https://facebook.com
            icon: ğŸ“˜
          - name: twitter
            link: https://twitter.com
            icon: ğŸ¦
          - name: instagram
            link: https://instagram.com
            icon: ğŸ“·
      - name: News
        links:
          - name: CNN
            link: https://cnn.com
            icon: ğŸ“°
          - name: BBC
            link: https://bbc.com
            icon: ğŸŒ
          - name: Reuters
            link: https://reuters.com
            icon: ğŸ—ï¸
      - name: Entertainment
        links:
          - name: YouTube
            link: https://youtube.com
            icon: ğŸ“º
          - name: Netflix
            link: https://netflix.com
            # icon for category links is optional
            # icon: ğŸ¬
          - name: Spotify
            link: https://spotify.com
            # icon: ğŸµ
      - name: Sports
        links:
          - name: ESPN
            link: https://espn.com
            icon: ":basketball:" # ğŸ€ emoji name
          - name: BBC Sport
            link: https://bbc.com/sport
            # Image file should be existing file path relative to cwd or config
            # file or dest html, and must be shipped with generated html file
            # with same relative path.
            icon: "bbc-sport.ico"
          - name: Sky Sports
            link: https://skysports.com
            icon: ğŸˆ
      - name: Shopping
        links:
          - name: Amazon
            link: https://amazon.com
            icon: ğŸ›’
          - name: eBay
            link: https://ebay.com
            icon: ğŸ’°
          - name: Walmart
            link: https://walmart.com
            icon: ğŸª
